### ISSUE TITLE
MVP #1 done.  Please approve

### ISSUE THREAD

**Issue by kallmeehkev** [kallmeehkev/Nomflix#2]
https://nomflix-aa-sf-may-19.herokuapp.com/#/

**Comment by ryan-mapa** [comment]
[ ] - enforce email field
[ ] - style logout
[ ] - capitalize invalid credentials error
[ ] - center errors (optional)

**Comment by kallmeehkev** [comment]
[x] - enforce email field
[x] - style logout
[x] - capitalize invalid credentials error
[ ] - center errors (optional)
